CREATE TABLE CUSTOMER(USERNAME VARCHAR(30) NOT NULL, PIN VARCHAR(5) NOT NULL, "First Name" VARCHAR(20), "Last Name" VARCHAR(20), "Address" VARCHAR(50), "City" VARCHAR(15), "State" VARCHAR(15),ZIP VARCHAR(5),"Card Type" VARCHAR(10),"Card Number" NUMERIC(16, 0),"Card Exp Date" DATE,"Cart ID" NUMERIC(6, 0), PRIMARY KEY (USERNAME),FOREIGN KEY ("Cart ID") REFERENCES SHOPPING_CART ON DELETE SET NULL);

CREATE TABLE SHOPPING_CART("Cart ID" NUMERIC(6, 0) NOT NULL, "Shipping and Handling" FLOAT, "Total Price" FLOAT,"Datetime" DATETIME, PRIMARY KEY ("Cart ID"));

CREATE TABLE "BOOK-SHOPPING_CART"("Cart ID" NUMERIC(6, 0) NOT NULL, ISBN NUMERIC(13, 0) NOT NULL, QUANTITY INTEGER NOT NULL, TOTAL_PRICE FLOAT, CHECK (QUANTITY > 0), PRIMARY KEY("Cart ID", ISBN), FOREIGN KEY ("Cart ID") REFERENCES SHOPPING_CART, FOREIGN KEY (ISBN) REFERENCES BOOK);

CREATE TABLE BOOK (ISBN NUMERIC(13, 0) NOT NULL, Title VARCHAR(100) NOT NULL,AUTHOR VARCHAR(40) NOT NULL, Publisher VARCHAR(40) NOT NULL, Price FLOAT, Category VARCHAR(20),INVENTORY INTEGER,CHECK (INVENTORY > 0),PRIMARY KEY (ISBN));

CREATE TABLE REVIEW ("Review ID" NUMERIC(6, 0) NOT NULL,"Description" VARCHAR(200) NOT NULL,ISBN NUMERIC(13, 0),PRIMARY KEY ("Review ID"), FOREIGN KEY (ISBN) REFERENCES BOOK ON DELETE SET NULL);

CREATE TABLE ADMINISTRATOR ("Admin Username" VARCHAR(30) NOT NULL, PIN VARCHAR(5) NOT NULL, PRIMARY KEY ("Admin Username"));
