CREATE TABLE CUSTOMER(Username VARCHAR(30) NOT NULL, PIN VARCHAR(5) NOT NULL, FirstName VARCHAR(20), LastName VARCHAR(20), Address VARCHAR(50), City VARCHAR(15), State VARCHAR(15),ZIP VARCHAR(5),CardType VARCHAR(10),CardNumber CHAR(16),CardExpDate CHAR(4),PRIMARY KEY (Username));

CREATE TABLE SHOPPING_CART(CartID NUMERIC(6, 0) NOT NULL, ShippingHandling FLOAT, TotalPrice FLOAT,"DateTime" DATETIME, PRIMARY KEY (CartID));

CREATE TABLE "BOOK-SHOPPING_CART"(CartID NUMERIC(6, 0) NOT NULL, ISBN NUMERIC(13, 0) NOT NULL, Quantity INTEGER NOT NULL, TotalPrice FLOAT, CHECK (Quantity > 0), PRIMARY KEY(CartID, ISBN), FOREIGN KEY (CartID) REFERENCES SHOPPING_CART, FOREIGN KEY (ISBN) REFERENCES BOOK);

CREATE TABLE BOOK (ISBN NUMERIC(13, 0) NOT NULL, Title VARCHAR(100) NOT NULL,Author VARCHAR(40) NOT NULL, Publisher VARCHAR(40) NOT NULL, Price FLOAT, Category VARCHAR(20),Inventory INTEGER,PRIMARY KEY (ISBN));

CREATE TABLE REVIEW (ReviewID INTEGER PRIMARY KEY,"Description" VARCHAR(200) NOT NULL,ISBN NUMERIC(13, 0), FOREIGN KEY (ISBN) REFERENCES BOOK ON DELETE SET NULL);

CREATE TABLE ADMINISTRATOR (Username VARCHAR(30) NOT NULL, PIN VARCHAR(5) NOT NULL, PRIMARY KEY (Username));
